"""tareasdefinitivo

Revision ID: 0810af67769a
Revises: 479ce702d0c4
Create Date: 2025-11-19 12:29:49.651610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0810af67769a'
down_revision: Union[str, Sequence[str], None] = '479ce702d0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dieta', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('tarea', 'usuario_asignado_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tarea', 'usuario_asignado_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('dieta', 'is_active')
    # ### end Alembic commands ###
