"""VETERINARIO3

Revision ID: 2b220190c38f
Revises: 53402791f007
Create Date: 2025-12-10 19:24:32.841074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b220190c38f'
down_revision: Union[str, Sequence[str], None] = '53402791f007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orden_examen', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('procedimiento_medico', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('procedimiento_medico', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('receta_medica', sa.Column('usuario_asignado_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'receta_medica', 'users', ['usuario_asignado_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receta_medica', type_='foreignkey')
    op.drop_column('receta_medica', 'usuario_asignado_id')
    op.drop_column('procedimiento_medico', 'updated_at')
    op.drop_column('procedimiento_medico', 'created_at')
    op.drop_column('orden_examen', 'updated_at')
    # ### end Alembic commands ###
