"""VETERINARIO2

Revision ID: 53402791f007
Revises: dd8ab1556164
Create Date: 2025-12-10 17:06:04.985147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53402791f007'
down_revision: Union[str, Sequence[str], None] = 'dd8ab1556164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_atencion',
    sa.Column('id_tipo_atencion', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo_atencion', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_atencion'),
    sa.UniqueConstraint('nombre_tipo_atencion')
    )
    op.create_index(op.f('ix_tipo_atencion_id_tipo_atencion'), 'tipo_atencion', ['id_tipo_atencion'], unique=False)
    op.create_table('tipo_examen',
    sa.Column('id_tipo_examen', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo_examen', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_examen'),
    sa.UniqueConstraint('nombre_tipo_examen')
    )
    op.create_index(op.f('ix_tipo_examen_id_tipo_examen'), 'tipo_examen', ['id_tipo_examen'], unique=False)
    op.create_table('historial_medico',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('veterinario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_atencion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_atencion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('anamnesis', sa.Text(), nullable=True),
    sa.Column('peso_actual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('temperatura', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('frecuencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('frecuencia_respiratoria', sa.Integer(), nullable=True),
    sa.Column('examen_fisico_obs', sa.Text(), nullable=True),
    sa.Column('diagnostico_presuntivo', sa.Text(), nullable=True),
    sa.Column('diagnostico_definitivo', sa.Text(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id_animal'], ),
    sa.ForeignKeyConstraint(['tipo_atencion_id'], ['tipo_atencion.id_tipo_atencion'], ),
    sa.ForeignKeyConstraint(['veterinario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_index(op.f('ix_historial_medico_animal_id'), 'historial_medico', ['animal_id'], unique=False)
    op.create_index(op.f('ix_historial_medico_id_historial'), 'historial_medico', ['id_historial'], unique=False)
    op.create_index(op.f('ix_historial_medico_veterinario_id'), 'historial_medico', ['veterinario_id'], unique=False)
    op.create_table('orden_examen',
    sa.Column('id_orden', sa.Integer(), nullable=False),
    sa.Column('historial_medico_id', sa.Integer(), nullable=False),
    sa.Column('tipo_examen_id', sa.Integer(), nullable=False),
    sa.Column('instrucciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['historial_medico_id'], ['historial_medico.id_historial'], ),
    sa.ForeignKeyConstraint(['tipo_examen_id'], ['tipo_examen.id_tipo_examen'], ),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_index(op.f('ix_orden_examen_id_orden'), 'orden_examen', ['id_orden'], unique=False)
    op.create_table('procedimiento_medico',
    sa.Column('id_procedimiento', sa.Integer(), nullable=False),
    sa.Column('historial_medico_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_programada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['historial_medico_id'], ['historial_medico.id_historial'], ),
    sa.PrimaryKeyConstraint('id_procedimiento')
    )
    op.create_index(op.f('ix_procedimiento_medico_id_procedimiento'), 'procedimiento_medico', ['id_procedimiento'], unique=False)
    op.create_table('receta_medica',
    sa.Column('id_receta', sa.Integer(), nullable=False),
    sa.Column('historial_medico_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=True),
    sa.Column('dosis', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('frecuencia', sa.String(length=100), nullable=False),
    sa.Column('duracion_dias', sa.Integer(), nullable=False),
    sa.Column('instrucciones_administracion', sa.Text(), nullable=True),
    sa.Column('generar_tarea_automatica', sa.Boolean(), nullable=False),
    sa.Column('frecuencia_cron', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['historial_medico_id'], ['historial_medico.id_historial'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidad_medida.id_unidad'], ),
    sa.PrimaryKeyConstraint('id_receta')
    )
    op.create_index(op.f('ix_receta_medica_id_receta'), 'receta_medica', ['id_receta'], unique=False)
    op.create_table('resultado_examen',
    sa.Column('id_resultado', sa.Integer(), nullable=False),
    sa.Column('orden_examen_id', sa.Integer(), nullable=False),
    sa.Column('fecha_resultado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('conclusiones', sa.Text(), nullable=True),
    sa.Column('archivo_url', sa.String(length=2048), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['orden_examen_id'], ['orden_examen.id_orden'], ),
    sa.PrimaryKeyConstraint('id_resultado')
    )
    op.create_index(op.f('ix_resultado_examen_id_resultado'), 'resultado_examen', ['id_resultado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultado_examen_id_resultado'), table_name='resultado_examen')
    op.drop_table('resultado_examen')
    op.drop_index(op.f('ix_receta_medica_id_receta'), table_name='receta_medica')
    op.drop_table('receta_medica')
    op.drop_index(op.f('ix_procedimiento_medico_id_procedimiento'), table_name='procedimiento_medico')
    op.drop_table('procedimiento_medico')
    op.drop_index(op.f('ix_orden_examen_id_orden'), table_name='orden_examen')
    op.drop_table('orden_examen')
    op.drop_index(op.f('ix_historial_medico_veterinario_id'), table_name='historial_medico')
    op.drop_index(op.f('ix_historial_medico_id_historial'), table_name='historial_medico')
    op.drop_index(op.f('ix_historial_medico_animal_id'), table_name='historial_medico')
    op.drop_table('historial_medico')
    op.drop_index(op.f('ix_tipo_examen_id_tipo_examen'), table_name='tipo_examen')
    op.drop_table('tipo_examen')
    op.drop_index(op.f('ix_tipo_atencion_id_tipo_atencion'), table_name='tipo_atencion')
    op.drop_table('tipo_atencion')
    # ### end Alembic commands ###
