"""TODO

Revision ID: 68ec98c1da8b
Revises: 
Create Date: 2025-09-18 23:59:40.079594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ec98c1da8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('climate_conditions', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habitats_id'), 'habitats', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=False),
    sa.Column('common_name', sa.String(length=150), nullable=False),
    sa.Column('phylum', sa.String(length=100), nullable=True),
    sa.Column('class_name', sa.String(length=100), nullable=True),
    sa.Column('order', sa.String(length=100), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('genus', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_id'), 'species', ['id'], unique=False)
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'UNKNOWN', name='genderenum'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('origin', sa.String(length=300), nullable=True),
    sa.Column('operational_status', sa.String(length=80), nullable=True),
    sa.Column('habitat_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitats.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=False)
    op.create_index(op.f('ix_animals_name'), 'animals', ['name'], unique=False)
    op.create_table('media_habitats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habitat_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_habitats_id'), 'media_habitats', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('TRIVIA',
    sa.Column('Id_trivia', sa.Integer(), nullable=False),
    sa.Column('Fecha_trivia', sa.DateTime(timezone=True), nullable=False),
    sa.Column('Cantidad_preguntas', sa.Integer(), nullable=False),
    sa.Column('Dificultad', sa.String(length=20), nullable=False),
    sa.Column('USUARIOS_Id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['USUARIOS_Id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('Id_trivia')
    )
    op.create_table('animal_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'animal_id', name='uq_user_animal_favorite')
    )
    op.create_index(op.f('ix_animal_favorites_id'), 'animal_favorites', ['id'], unique=False)
    op.create_table('encuestas',
    sa.Column('id_encuesta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario_creador_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_encuesta')
    )
    op.create_table('media_animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'OTHER', name='mediatypeenum'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_animals_id'), 'media_animals', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=128), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_info', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_table('PARTICIPACIONES_TRIVIA',
    sa.Column('Id_participacion_trivia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('USUARIOS_Id_usuario', sa.Integer(), nullable=False),
    sa.Column('Aciertos', sa.Integer(), nullable=False),
    sa.Column('Fecha_trivia', sa.DateTime(timezone=True), nullable=False),
    sa.Column('TRIVIA_Id_trivia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['TRIVIA_Id_trivia'], ['TRIVIA.Id_trivia'], ),
    sa.ForeignKeyConstraint(['USUARIOS_Id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('Id_participacion_trivia')
    )
    op.create_table('encuesta_tema',
    sa.Column('id_tema', sa.Integer(), nullable=False),
    sa.Column('tipo_tema', sa.String(length=50), nullable=False),
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['encuesta_id'], ['encuestas.id_encuesta'], ),
    sa.PrimaryKeyConstraint('id_tema', 'tipo_tema', 'encuesta_id')
    )
    op.create_table('participaciones_encuesta',
    sa.Column('id_participacion', sa.Integer(), nullable=False),
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_participacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['encuesta_id'], ['encuestas.id_encuesta'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_participacion')
    )
    op.create_table('preguntas_encuesta',
    sa.Column('id_pregunta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.Column('texto_pregunta', sa.String(length=100), nullable=False),
    sa.Column('es_opcion_unica', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encuesta_id'], ['encuestas.id_encuesta'], ),
    sa.PrimaryKeyConstraint('id_pregunta')
    )
    op.create_table('opcion_encuesta',
    sa.Column('id_opcion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('texto_opcion', sa.String(length=200), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas_encuesta.id_pregunta'], ),
    sa.PrimaryKeyConstraint('id_opcion')
    )
    op.create_table('respuesta_usuario',
    sa.Column('id_respuesta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participacion_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('opcion_id', sa.Integer(), nullable=True),
    sa.Column('respuesta_texto', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['opcion_id'], ['opcion_encuesta.id_opcion'], ),
    sa.ForeignKeyConstraint(['participacion_id'], ['participaciones_encuesta.id_participacion'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas_encuesta.id_pregunta'], ),
    sa.PrimaryKeyConstraint('id_respuesta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuesta_usuario')
    op.drop_table('opcion_encuesta')
    op.drop_table('preguntas_encuesta')
    op.drop_table('participaciones_encuesta')
    op.drop_table('encuesta_tema')
    op.drop_table('PARTICIPACIONES_TRIVIA')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_media_animals_id'), table_name='media_animals')
    op.drop_table('media_animals')
    op.drop_table('encuestas')
    op.drop_index(op.f('ix_animal_favorites_id'), table_name='animal_favorites')
    op.drop_table('animal_favorites')
    op.drop_table('TRIVIA')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_media_habitats_id'), table_name='media_habitats')
    op.drop_table('media_habitats')
    op.drop_index(op.f('ix_animals_name'), table_name='animals')
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_species_id'), table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_habitats_id'), table_name='habitats')
    op.drop_table('habitats')
    # ### end Alembic commands ###
