"""tareasdefinitivo3

Revision ID: 71afc3d94cb9
Revises: 99a960338453
Create Date: 2025-11-22 17:52:48.434769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71afc3d94cb9'
down_revision: Union[str, Sequence[str], None] = '99a960338453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tarea_recurrente', 'usuario_asignado_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tarea_recurrente', 'usuario_asignado_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
