"""tareasdefinitivo4

Revision ID: 8e8efd8fcfaf
Revises: 71afc3d94cb9
Create Date: 2025-11-22 21:07:41.941781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8efd8fcfaf'
down_revision: Union[str, Sequence[str], None] = '71afc3d94cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_salidas', sa.Column('habitat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detalle_salidas', 'habitats', ['habitat_id'], ['id_habitat'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalle_salidas', type_='foreignkey')
    op.drop_column('detalle_salidas', 'habitat_id')
    # ### end Alembic commands ###
