"""Todo de nuevo

Revision ID: 92077e0675e8
Revises: 
Create Date: 2025-10-26 20:00:26.006286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92077e0675e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especies',
    sa.Column('id_especie', sa.Integer(), nullable=False),
    sa.Column('nombre_cientifico', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('filo', sa.String(length=100), nullable=False),
    sa.Column('clase', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.String(length=100), nullable=False),
    sa.Column('familia', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_especie'),
    sa.UniqueConstraint('nombre_cientifico')
    )
    op.create_table('habitats',
    sa.Column('id_habitat', sa.Integer(), nullable=False),
    sa.Column('nombre_habitat', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('condiciones_climaticas', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_habitat')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('animals',
    sa.Column('id_animal', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('especies_id_especie', sa.Integer(), nullable=False),
    sa.Column('genero', sa.Boolean(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('procedencia', sa.String(length=300), nullable=False),
    sa.Column('estado_operativo', sa.Enum('SALUDABLE', 'EN_TRATAMIENTO', 'EN_CUARENTENA', 'TRASLADADO', 'FALLECIDO', name='animalstate'), nullable=False),
    sa.Column('habitats_id_habitat', sa.Integer(), nullable=False),
    sa.Column('es_publico', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['especies_id_especie'], ['especies.id_especie'], ),
    sa.ForeignKeyConstraint(['habitats_id_habitat'], ['habitats.id_habitat'], ),
    sa.PrimaryKeyConstraint('id_animal')
    )
    op.create_table('media_habitats',
    sa.Column('id_media_habitat', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('habitats_id_habitat', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['habitats_id_habitat'], ['habitats.id_habitat'], ),
    sa.PrimaryKeyConstraint('id_media_habitat')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=2048), nullable=True),
    sa.Column('is_totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('TRIVIA',
    sa.Column('Id_trivia', sa.Integer(), nullable=False),
    sa.Column('Fecha_trivia', sa.DateTime(timezone=True), nullable=False),
    sa.Column('Cantidad_preguntas', sa.Integer(), nullable=False),
    sa.Column('Dificultad', sa.String(length=20), nullable=False),
    sa.Column('USUARIOS_Id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['USUARIOS_Id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('Id_trivia')
    )
    op.create_table('animalfavorito',
    sa.Column('id_animal_favorito', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_guardado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuarios_id_usuario', sa.Integer(), nullable=False),
    sa.Column('animals_id_animal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animals_id_animal'], ['animals.id_animal'], ),
    sa.ForeignKeyConstraint(['usuarios_id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_animal_favorito')
    )
    op.create_table('encuestas',
    sa.Column('id_encuesta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario_creador_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_encuesta')
    )
    op.create_table('media_animal',
    sa.Column('id_media', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('animals_id_animal', sa.Integer(), nullable=False),
    sa.Column('tipo_medio', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['animals_id_animal'], ['animals.id_animal'], ),
    sa.PrimaryKeyConstraint('id_media')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=128), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_info', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_table('two_factor_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_two_factor_codes_id'), 'two_factor_codes', ['id'], unique=False)
    op.create_table('PARTICIPACIONES_TRIVIA',
    sa.Column('Id_participacion_trivia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('USUARIOS_Id_usuario', sa.Integer(), nullable=False),
    sa.Column('Aciertos', sa.Integer(), nullable=False),
    sa.Column('Fecha_trivia', sa.DateTime(timezone=True), nullable=False),
    sa.Column('TRIVIA_Id_trivia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['TRIVIA_Id_trivia'], ['TRIVIA.Id_trivia'], ),
    sa.ForeignKeyConstraint(['USUARIOS_Id_usuario'], ['users.id'], ),
    sa.PrimaryKeyConstraint('Id_participacion_trivia')
    )
    op.create_table('encuesta_tema',
    sa.Column('id_tema', sa.Integer(), nullable=False),
    sa.Column('tipo_tema', sa.String(length=50), nullable=False),
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['encuesta_id'], ['encuestas.id_encuesta'], ),
    sa.PrimaryKeyConstraint('id_tema', 'tipo_tema', 'encuesta_id')
    )
    op.create_table('participaciones_encuesta',
    sa.Column('id_participacion', sa.Integer(), nullable=False),
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_participacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['encuesta_id'], ['encuestas.id_encuesta'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_participacion')
    )
    op.create_table('preguntas_encuesta',
    sa.Column('id_pregunta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('encuesta_id', sa.Integer(), nullable=False),
    sa.Column('texto_pregunta', sa.String(length=100), nullable=False),
    sa.Column('es_opcion_unica', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encuesta_id'], ['encuestas.id_encuesta'], ),
    sa.PrimaryKeyConstraint('id_pregunta')
    )
    op.create_table('opcion_encuesta',
    sa.Column('id_opcion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('texto_opcion', sa.String(length=200), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas_encuesta.id_pregunta'], ),
    sa.PrimaryKeyConstraint('id_opcion')
    )
    op.create_table('respuesta_usuario',
    sa.Column('id_respuesta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participacion_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('opcion_id', sa.Integer(), nullable=True),
    sa.Column('respuesta_texto', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['opcion_id'], ['opcion_encuesta.id_opcion'], ),
    sa.ForeignKeyConstraint(['participacion_id'], ['participaciones_encuesta.id_participacion'], ),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas_encuesta.id_pregunta'], ),
    sa.PrimaryKeyConstraint('id_respuesta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuesta_usuario')
    op.drop_table('opcion_encuesta')
    op.drop_table('preguntas_encuesta')
    op.drop_table('participaciones_encuesta')
    op.drop_table('encuesta_tema')
    op.drop_table('PARTICIPACIONES_TRIVIA')
    op.drop_index(op.f('ix_two_factor_codes_id'), table_name='two_factor_codes')
    op.drop_table('two_factor_codes')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('media_animal')
    op.drop_table('encuestas')
    op.drop_table('animalfavorito')
    op.drop_table('TRIVIA')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('media_habitats')
    op.drop_table('animals')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('habitats')
    op.drop_table('especies')
    # ### end Alembic commands ###
