"""tareasdefinitivo2

Revision ID: 99a960338453
Revises: 0810af67769a
Create Date: 2025-11-20 00:51:25.318977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a960338453'
down_revision: Union[str, Sequence[str], None] = '0810af67769a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_salidas',
    sa.Column('id_tipo_salida', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo_salida', sa.String(length=100), nullable=False),
    sa.Column('descripcion_tipo_salida', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_salida'),
    sa.UniqueConstraint('nombre_tipo_salida')
    )
    op.create_index(op.f('ix_tipo_salidas_id_tipo_salida'), 'tipo_salidas', ['id_tipo_salida'], unique=False)
    op.add_column('salidas', sa.Column('tipo_salida_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'salidas', 'tipo_salidas', ['tipo_salida_id'], ['id_tipo_salida'])
    op.drop_column('salidas', 'tipo_salida')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salidas', sa.Column('tipo_salida', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'salidas', type_='foreignkey')
    op.drop_column('salidas', 'tipo_salida_id')
    op.drop_index(op.f('ix_tipo_salidas_id_tipo_salida'), table_name='tipo_salidas')
    op.drop_table('tipo_salidas')
    # ### end Alembic commands ###
