"""NUEVO

Revision ID: 9ac711d94a8c
Revises: 96ebb1d91918
Create Date: 2025-09-23 12:12:40.273491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac711d94a8c'
down_revision: Union[str, Sequence[str], None] = '96ebb1d91918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_animal', 'tipo_medio',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_animal', 'tipo_medio',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
