"""inventario3

Revision ID: bce8bc40f22b
Revises: 9d19d196a28a
Create Date: 2025-11-12 00:02:02.938965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce8bc40f22b'
down_revision: Union[str, Sequence[str], None] = '9d19d196a28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=100), nullable=False),
    sa.Column('telefono_proveedor', sa.String(length=25), nullable=True),
    sa.Column('email_proveedor', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_proveedor'),
    sa.UniqueConstraint('nombre_proveedor')
    )
    op.create_index(op.f('ix_proveedores_email_proveedor'), 'proveedores', ['email_proveedor'], unique=True)
    op.create_index(op.f('ix_proveedores_id_proveedor'), 'proveedores', ['id_proveedor'], unique=False)
    op.create_table('tipo_producto',
    sa.Column('id_tipo_producto', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo_producto', sa.String(length=100), nullable=False),
    sa.Column('descripcion_tipo_producto', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_producto'),
    sa.UniqueConstraint('nombre_tipo_producto')
    )
    op.create_index(op.f('ix_tipo_producto_id_tipo_producto'), 'tipo_producto', ['id_tipo_producto'], unique=False)
    op.create_table('unidad_medida',
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('nombre_unidad', sa.String(length=100), nullable=False),
    sa.Column('abreviatura', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_unidad'),
    sa.UniqueConstraint('abreviatura'),
    sa.UniqueConstraint('nombre_unidad')
    )
    op.create_index(op.f('ix_unidad_medida_id_unidad'), 'unidad_medida', ['id_unidad'], unique=False)
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(length=200), nullable=False),
    sa.Column('descripcion_producto', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=2048), nullable=True),
    sa.Column('public_id', sa.String(length=255), nullable=True),
    sa.Column('stock_actual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tipo_producto_id', sa.Integer(), nullable=False),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tipo_producto_id'], ['tipo_producto.id_tipo_producto'], ),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidad_medida.id_unidad'], ),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('nombre_producto')
    )
    op.create_index(op.f('ix_productos_id_producto'), 'productos', ['id_producto'], unique=False)
    op.create_table('entradas_inventario',
    sa.Column('id_entrada_inventario', sa.Integer(), nullable=False),
    sa.Column('fecha_entrada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id_proveedor'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_entrada_inventario')
    )
    op.create_index(op.f('ix_entradas_inventario_id_entrada_inventario'), 'entradas_inventario', ['id_entrada_inventario'], unique=False)
    op.create_table('salidas',
    sa.Column('id_salida', sa.Integer(), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_salida', sa.String(length=100), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_salida')
    )
    op.create_index(op.f('ix_salidas_id_salida'), 'salidas', ['id_salida'], unique=False)
    op.create_table('stock_lote',
    sa.Column('id_stocklote', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=False),
    sa.Column('fecha_caducidad', sa.Date(), nullable=False),
    sa.Column('cantidad_disponible', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad_disponible >= 0', name='chk_cantidad_disponible_no_negativa'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_stocklote')
    )
    op.create_index(op.f('ix_stock_lote_fecha_caducidad'), 'stock_lote', ['fecha_caducidad'], unique=False)
    op.create_index(op.f('ix_stock_lote_id_stocklote'), 'stock_lote', ['id_stocklote'], unique=False)
    op.create_index(op.f('ix_stock_lote_lote'), 'stock_lote', ['lote'], unique=False)
    op.create_index(op.f('ix_stock_lote_producto_id'), 'stock_lote', ['producto_id'], unique=False)
    op.create_table('detalle_entrada',
    sa.Column('id_detalle_entrada', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_entrada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_caducidad', sa.Date(), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['entrada_id'], ['entradas_inventario.id_entrada_inventario'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle_entrada')
    )
    op.create_index(op.f('ix_detalle_entrada_id_detalle_entrada'), 'detalle_entrada', ['id_detalle_entrada'], unique=False)
    op.create_table('detalle_salidas',
    sa.Column('id_detalle_salida', sa.Integer(), nullable=False),
    sa.Column('salida_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_salida', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id_animal'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['salida_id'], ['salidas.id_salida'], ),
    sa.PrimaryKeyConstraint('id_detalle_salida')
    )
    op.create_index(op.f('ix_detalle_salidas_id_detalle_salida'), 'detalle_salidas', ['id_detalle_salida'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_salidas_id_detalle_salida'), table_name='detalle_salidas')
    op.drop_table('detalle_salidas')
    op.drop_index(op.f('ix_detalle_entrada_id_detalle_entrada'), table_name='detalle_entrada')
    op.drop_table('detalle_entrada')
    op.drop_index(op.f('ix_stock_lote_producto_id'), table_name='stock_lote')
    op.drop_index(op.f('ix_stock_lote_lote'), table_name='stock_lote')
    op.drop_index(op.f('ix_stock_lote_id_stocklote'), table_name='stock_lote')
    op.drop_index(op.f('ix_stock_lote_fecha_caducidad'), table_name='stock_lote')
    op.drop_table('stock_lote')
    op.drop_index(op.f('ix_salidas_id_salida'), table_name='salidas')
    op.drop_table('salidas')
    op.drop_index(op.f('ix_entradas_inventario_id_entrada_inventario'), table_name='entradas_inventario')
    op.drop_table('entradas_inventario')
    op.drop_index(op.f('ix_productos_id_producto'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_unidad_medida_id_unidad'), table_name='unidad_medida')
    op.drop_table('unidad_medida')
    op.drop_index(op.f('ix_tipo_producto_id_tipo_producto'), table_name='tipo_producto')
    op.drop_table('tipo_producto')
    op.drop_index(op.f('ix_proveedores_id_proveedor'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_email_proveedor'), table_name='proveedores')
    op.drop_table('proveedores')
    # ### end Alembic commands ###
