"""tareas

Revision ID: dddc83afef2d
Revises: bce8bc40f22b
Create Date: 2025-11-14 23:56:53.062308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dddc83afef2d'
down_revision: Union[str, Sequence[str], None] = 'bce8bc40f22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_tarea',
    sa.Column('id_tipo_tarea', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo_tarea', sa.String(length=100), nullable=False),
    sa.Column('descripcion_tipo_tarea', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_tarea'),
    sa.UniqueConstraint('nombre_tipo_tarea')
    )
    op.create_index(op.f('ix_tipo_tarea_id_tipo_tarea'), 'tipo_tarea', ['id_tipo_tarea'], unique=False)
    op.create_table('dieta',
    sa.Column('id_dieta', sa.Integer(), nullable=False),
    sa.Column('nombre_dieta', sa.String(length=100), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('especie_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('animal_id IS NOT NULL OR especie_id IS NOT NULL', name='chk_dieta_target'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id_animal'], ),
    sa.ForeignKeyConstraint(['especie_id'], ['especies.id_especie'], ),
    sa.PrimaryKeyConstraint('id_dieta'),
    sa.UniqueConstraint('animal_id', name='uq_dieta_animal_id'),
    sa.UniqueConstraint('especie_id', name='uq_dieta_especie_id'),
    sa.UniqueConstraint('nombre_dieta')
    )
    op.create_index(op.f('ix_dieta_id_dieta'), 'dieta', ['id_dieta'], unique=False)
    op.create_table('tarea_recurrente',
    sa.Column('id_tarea_recurrente', sa.Integer(), nullable=False),
    sa.Column('titulo_plantilla', sa.String(length=255), nullable=False),
    sa.Column('descripcion_plantilla', sa.Text(), nullable=True),
    sa.Column('tipo_tarea_id', sa.Integer(), nullable=False),
    sa.Column('usuario_asignado_id', sa.Integer(), nullable=False),
    sa.Column('frecuencia_cron', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('habitat_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id_animal'], ),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitats.id_habitat'], ),
    sa.ForeignKeyConstraint(['tipo_tarea_id'], ['tipo_tarea.id_tipo_tarea'], ),
    sa.ForeignKeyConstraint(['usuario_asignado_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_tarea_recurrente')
    )
    op.create_index(op.f('ix_tarea_recurrente_id_tarea_recurrente'), 'tarea_recurrente', ['id_tarea_recurrente'], unique=False)
    op.create_table('detalle_dieta',
    sa.Column('id_detalle_dieta', sa.Integer(), nullable=False),
    sa.Column('dieta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('frecuencia', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dieta_id'], ['dieta.id_dieta'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidad_medida.id_unidad'], ),
    sa.PrimaryKeyConstraint('id_detalle_dieta')
    )
    op.create_index(op.f('ix_detalle_dieta_id_detalle_dieta'), 'detalle_dieta', ['id_detalle_dieta'], unique=False)
    op.create_table('tarea',
    sa.Column('id_tarea', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion_tarea', sa.Text(), nullable=True),
    sa.Column('usuario_asignado_id', sa.Integer(), nullable=False),
    sa.Column('tipo_tarea_id', sa.Integer(), nullable=False),
    sa.Column('fecha_programada', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('fecha_completada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas_completacion', sa.Text(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('habitat_id', sa.Integer(), nullable=True),
    sa.Column('tarea_recurrente_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id_animal'], ),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitats.id_habitat'], ),
    sa.ForeignKeyConstraint(['tarea_recurrente_id'], ['tarea_recurrente.id_tarea_recurrente'], ),
    sa.ForeignKeyConstraint(['tipo_tarea_id'], ['tipo_tarea.id_tipo_tarea'], ),
    sa.ForeignKeyConstraint(['usuario_asignado_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_tarea')
    )
    op.create_index(op.f('ix_tarea_fecha_programada'), 'tarea', ['fecha_programada'], unique=False)
    op.create_index(op.f('ix_tarea_id_tarea'), 'tarea', ['id_tarea'], unique=False)
    op.create_index(op.f('ix_tarea_is_completed'), 'tarea', ['is_completed'], unique=False)
    op.create_index(op.f('ix_tarea_tipo_tarea_id'), 'tarea', ['tipo_tarea_id'], unique=False)
    op.create_index(op.f('ix_tarea_usuario_asignado_id'), 'tarea', ['usuario_asignado_id'], unique=False)
    op.create_table('registro_alimentacion',
    sa.Column('id_registro_alimentacion', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_alimentacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notas_observaciones', sa.Text(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('habitat_id', sa.Integer(), nullable=True),
    sa.Column('tarea_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('animal_id IS NOT NULL OR habitat_id IS NOT NULL', name='chk_registro_alimentacion_target'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id_animal'], ),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitats.id_habitat'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tarea.id_tarea'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_registro_alimentacion'),
    sa.UniqueConstraint('tarea_id')
    )
    op.create_index(op.f('ix_registro_alimentacion_id_registro_alimentacion'), 'registro_alimentacion', ['id_registro_alimentacion'], unique=False)
    op.create_table('detalle_alimentacion',
    sa.Column('id_detalle_alimentacion', sa.Integer(), nullable=False),
    sa.Column('registro_alimentacion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_entregada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad_consumida', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['registro_alimentacion_id'], ['registro_alimentacion.id_registro_alimentacion'], ),
    sa.PrimaryKeyConstraint('id_detalle_alimentacion')
    )
    op.create_index(op.f('ix_detalle_alimentacion_id_detalle_alimentacion'), 'detalle_alimentacion', ['id_detalle_alimentacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_alimentacion_id_detalle_alimentacion'), table_name='detalle_alimentacion')
    op.drop_table('detalle_alimentacion')
    op.drop_index(op.f('ix_registro_alimentacion_id_registro_alimentacion'), table_name='registro_alimentacion')
    op.drop_table('registro_alimentacion')
    op.drop_index(op.f('ix_tarea_usuario_asignado_id'), table_name='tarea')
    op.drop_index(op.f('ix_tarea_tipo_tarea_id'), table_name='tarea')
    op.drop_index(op.f('ix_tarea_is_completed'), table_name='tarea')
    op.drop_index(op.f('ix_tarea_id_tarea'), table_name='tarea')
    op.drop_index(op.f('ix_tarea_fecha_programada'), table_name='tarea')
    op.drop_table('tarea')
    op.drop_index(op.f('ix_detalle_dieta_id_detalle_dieta'), table_name='detalle_dieta')
    op.drop_table('detalle_dieta')
    op.drop_index(op.f('ix_tarea_recurrente_id_tarea_recurrente'), table_name='tarea_recurrente')
    op.drop_table('tarea_recurrente')
    op.drop_index(op.f('ix_dieta_id_dieta'), table_name='dieta')
    op.drop_table('dieta')
    op.drop_index(op.f('ix_tipo_tarea_id_tipo_tarea'), table_name='tipo_tarea')
    op.drop_table('tipo_tarea')
    # ### end Alembic commands ###
